### ISSUE TITLE
MahApps.Metro is not compatible with GPL-v2

### ISSUE THREAD

**Issue by jassmith** [HearthSim/Hearthstone-Deck-Tracker#1447]
Hearthstone-Deck-Tracker is licenses GPLv2 and depends on MahApps.Metro which is licensed MS-PL. MS-PL is not a GPLv2 compatible and also not GPLv3 compatibile. This presents an issue both for you as the developer as well as your users :/

I would recommend switching to MIT or MS-PL here. You should probably do this sooner than later to avoid having to get sign off from contributors you can no longer track down.

**Comment by Epix37** [comment]
Are you sure?
http://stackoverflow.com/a/1424334

**Comment by jassmith** [comment]
http://lwn.net/Articles/254717/

Fairly certain. Had to deal with licensing shit a lot when I worked on Ubuntu for Canonical. Basically MSPL is a FSF approved FOSS license that is GPL incompatible.

**Comment by Epix37** [comment]
> No.  Neither license is GPL compatible, since they both require source redistribution under
the original license.
...
> The catch is, *if* you distribute the source, you must distribute it under the MSPL license.
You *can't* combine it into a GPL project.  This seems designed gratuitously to break GPL
compatibility.

I am not distributing it in source form though.

**Comment by Otto42** [comment]
Preface: IANAL, this is not legal advice.

There is some ambiguity here, and in this case, it actually kind of matters. Long read incoming. Sorry if you dislike long reads. :)

On the surface, yes, the MS-PL license is incompatible with the GPL. Perhaps delibrately so. However, there are ramifications to how licenses interact and how copyright works that also need to be taken into account.

The MS-PL is basically a BSD-Style license, with clause 3D in it. Since you're not distributing the source of the software, then this line applies:

"If you distribute any portion of the software in compiled or object code form, you may only do so under a license that complies with this license."

The question is whether or not your license complies with the rest of the license. That depends, really. You could easily state that the metro dll files are distributed under the MS-PL and the rest is under your own license. Since you didn't modify the metro dll files, really, then you wouldn't have any reason to relicense them anyway.

Now, some will tell you that this is actually not okay. The FSF and others have this concept of "deep-linking". Basically, they say that if it's all executable code forming the same program, then it's really the same program. 

However, what some will miss is that this only works in one direction, from GPL licensed libraries to other code using those libraries. Here you have the opposite case. The library is licensed in such a way that you could easily read the MS-PL piece as saying that only the library itself needs to remain under MS-PL. It's not a "viral" license.

This all comes down to the question of "what is a derivative work"? Again, if you believe the FSF, then using a library in a "deep" fashion would make your work a derivative one. But at the same time, they don't state that you cannot make GPL software which runs on Windows. All Windows code uses parts of the operating system, lots of it in DLLs, and lots of those libraries are definitely not open source, in any sense of the term.

Basically, the question of license always comes down to two simple questions: who can sue who, and will they win?

Since the Mahapps.Metro creators are the ones who hold the copyright, they are the only ones that have standing to bring suit against you for violation of their license. Are they likely to do so? Since they actually list this project on their About page, I'd rate that as unlikely: http://mahapps.com/about/

Would they win? Well, that's a question to ask a qualified lawyer about.

The GPL does have an out though. The "mere aggregation" clause states that "mere aggregation of another work not based on the Program ... does not bring the other work under the scope of this License". Since in no-way can Mahapps.Metro be said to be derivative of HDT, then you can simply state that it's licensed under MS-PL and everything else you have written is GPL. Simple. 

Some may object, but the only objection that actually matters is that of the authors of Mahapps.Metro. If they give permission, then you're fine. They're not bound by licenses, they hold the copyright. Licenses only apply to licensees.

**Comment by Fyren** [comment]
I'm also not a lawyer, but am a developer.  Not distributing it in source isn't what matters.

If you believe the FSF's take on linking, if your program is linked at all, that's no good.  This includes dynamic loading of libraries.  There's no "deep" use or "light" use or anything else.  The separation they want would require using pipes or sockets between the two pieces of code.  This is from GPLv2 section 2 and the FSF's FAQ about the GPL.

However, the reason you can use Windows system DLLs is there is an explicit "system library" exception in the GPL.  This is in GPLv2 section 3.

The intent of the GPL is if you have a GPL application, you can get the source for the entire thing and not in a way that's more restrictive than the GPL provides.  The MS-PL requirement of using MS-PL is such a restriction beyond the GPL.

**Comment by jassmith** [comment]
Things get even muddier when you start thinking about what it means to contribute code to a project effectively in violation of its own license. Sure the original code can be re-licensed by the original authors, but this would require permission from every contributor as well. If such a contributor were to refuse to re-license you would be forced to back out all of their changes and re-implement them.

**Comment by Fyren** [comment]
That's one reason why some projects require contributors to assign the copyright of contributions to the original author or an organization controlling the project.  Even just reimplementing is sticky because if you read their commits then someone litigious could argue it's still derivative as it's not a clean room reimplementation.

**Comment by jassmith** [comment]
I just noticed it looks like the project has gone back under a proprietary license.

**Comment by Epix37** [comment]
Thank you guys for all the information!

@jassmith Yea, I removed the license again after you posted this. 

Okay, so no GPL. The options are indeed MIT or MS-PL then, I suppose.
