### ISSUE TITLE
Stats tab - redesing + pie charts

### ISSUE THREAD

**Issue by Cu8eR** [HearthSim/Hearthstone-Deck-Tracker#1603]
It would be nice to have a tab with complete stats, I really love your Deck Tracker, one of the best... just one thing should be added/improved - better stats handling.

I used this tracker one year ago, then I moved to yours one. I loved the stats screen and really nice and user-friendly UI for this purpose 

http://hearthstonetracker.com/screenshots#

I really like this concept:
https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/799

also some ideas:
http://hearthstats.net/decks/tobias-necromantik--12/public_show?locale=en

really like the stats about "no coin and with coins wins"

**Comment by Epix37** [comment]
This is one of the next things on my todo list.

**Comment by anonymous555** [comment]
See https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1045

**Comment by Cu8eR** [comment]
@anonymous555 - I see, but we need more stats. I really like the way how they are shown here: http://hearthstonetracker.com/screenshots#

Also @Epix37 has already done some changes here #799 , it is a good starting point. I would like to you only all-in-one tracker with everything inside. Now we have really nice tracker with a plenty of features, only stats missing. With them it would be masterpiece!

**Comment by Epix37** [comment]
WIP: http://imgur.com/a/0X8F5

**Comment by Cu8eR** [comment]
@Epix37 - this is really nice! Good job!

I would like to see total time for every deck/class I have been playing

+ is there any text (legend) on mouse hover?

**Comment by Epix37** [comment]
You can see the total time for runs in the 2nd screenshot, adding the time to the highlights panels is a good idea.

Tooltips for what/where? All charts elements, class icons and packs/cards cells have tooltips atm.

(**this is only arena so far**, I have not started on constructed yet)

**Comment by Cu8eR** [comment]
Oh, now I see :)

Good job, I am waiting to final release

**Comment by GiggliG** [comment]
That looks really good. There's a typo on the opponent's panel "Opponenets"

For Constructed, here are some stats features I'd like to see, mostly different filters:
* Filter by server
* Filter by Mode (checkbox, so you can combine seperate modes - so see stats of Casual + ranked, for instance)
* Filter by Time (season/month mainly, but again the ability to combine them via checkboxes rather than radio buttons)
* Custom time filter: set start date and end date
* Filter by Tag - its possible to filter by tag alrteady, but its clunky, you have to set the universal deck filter first.

Also, I'd like the month tracking to include correct time zone offset for each server.
HS's month starts a different time in EU and US and Asia servers, and this means there are some errors when looking at monthly stats especially if you play in a different time zone to the one blizzard uses.

**Comment by Elitesparkle** [comment]
In case you need some suggestions, see my old issue about this topic: #586.

**Comment by Cu8eR** [comment]
I hope this will be implemented in v0.14.x... according to the commits. Thank you!

**Comment by Epix37** [comment]
I think I got everything done I want to get in to the next update now, check it out: http://imgur.com/a/Fllcn

Line charts to show rank/winrate progress as well as maybe a few other ones should come eventually, I wouldn't have time to add that before the patch hits though.

Almost everything works with almost all the filters (few exceptions, like the matchups table doesn't care about the set classes). This allows for some pretty specific statistics, like e.g. the average match time for "wins vs druid from rank 3-5, in season 19-23".

When selecting 'active deck only' the matchups table is swapped out with the version breakdown one for that deck.

**Comment by Cu8eR** [comment]
Perfect! Thank you again. I am looking forward to test it and I hope that you will add more features into this later ;)

**Comment by Epix37** [comment]
Pre-release: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v0.14.3

**Comment by Epix37** [comment]
Added  with v0.14.4.
