### ISSUE TITLE
Record GOLDEN hero opponents

### ISSUE THREAD

**Issue by pagem** [HearthSim/Hearthstone-Deck-Tracker#2118]
Enhancement request - Is there anyway to capture in the match results if the opponent was a GOLDEN hero?

**Comment by Epix37** [comment]
That's possible, yes.

Are you specifically talking about 500-wins golden or the bought ones?

**Comment by pagem** [comment]
The 500 win GOLDEN heroes. Maybe an indication of a better player...

**Comment by culinko** [comment]
I'd like to see hero skins too, so you could compare how many people bought them.

**Comment by Cu8eR** [comment]
I think that golden heroes are enough

**Comment by culinko** [comment]
Why is it that you are the only one here who ever responds with a response that essentially means "No, we don't want that feature"? I don't need half of the things suggested in other issues myself, but that doesn't mean I should tell Epix to not try to implement them, because I know that other people do want them. Also, both of the things mentioned here are relatively easy to get from the log, "tag=PREMIUM value=1" for golden hero,"FULL_ENTITY - Creating ID=64 CardID=HERO_01a" for Magni Bronzebeard. The only question is how to display them, probably a text on hovering the class icon for hero name? A golden border around the class for the golden hero? I am not an UI designer, so if anyone knows of a more elegant way to display both of the things mentioned, feel free to give feedback.

**Comment by Cu8eR** [comment]
Welcome in democracy :) maybe you dont have this in your country ;)

**Comment by AlbertoOS** [comment]
[Don't be an asshole.](http://cdn.someecards.com/someecards/usercards/1320879498132_1281971.png)

**Comment by Epix37** [comment]
^ that. I'll remove the past hour on this. The next time you will be blocked.

**Comment by azeier** [comment]
This is recorded by hsreplay.net
