### ISSUE TITLE
Potential (accidental) unallowed behavior on behalf of the tracker

### ISSUE THREAD

**Issue by ticowiko** [HearthSim/Hearthstone-Deck-Tracker#2421]
I was playing a C'Thun priest deck against a mage, and he ended up with a Hooded Acolyte using mirror entity. At this point, his C'Thun counter had not activated because he had not yet played any C'Thun boosting cards. In fact, he was clearly not playing a C'Thun deck. Now here's the problem : at this point, I decide to heal one of my minions, and this activates his Hooded Acolyte... which doesn't make his C'Thun counter appear. So what happened here ? Does the tracker somehow know he doesn't have a C'Thun ? Again, for me, it was clear he didn't have it. But how did the tracker know ? Is that info somehow in memory and the tracker read it ? If so, doesn't this break the "trackers may only do what pen and paper can do" rule set by Blizzard ?

**Comment by GaryKing** [comment]
I'm pretty sure that HDT does not know that the opponent didn't have C'Thun. HDT only knows what the servers tells it. The reason it didn't show the counter is because this is basically a bug.

In my opinion, HDT should have showed the C'Thun counter once they have a minion that procs C'Thun, like in your case. HDT shouldn't assume that the opponent is playing a C'Thun deck once they have any minion that procs C'Thun, since that's the safer assumption. I have definitely played C'Thun without ever playing any C'Thun buff cards, although yes it is rare.

**Comment by GaryKing** [comment]
One thing I noticed was that in the current Brawl, I played as Warlock and I played a C'Thun buff card. The image of C'Thun did not appear as it normally does. So it only appears if I have C'Thun in my deck? Then if HDT could somehow piggyback off of that animation, and only show the counter when that graphic appears, then that would make sense too.

Note that I was in no-deck mode since I was playing a Brawl, so HDT couldn't have known if I had C'Thun in my deck or not.

**Comment by Epix37** [comment]
You healing the Acolyte also made no C'Thun apper on the board for him, right? That's essentially the data HDT uses. 

The C'Thun counter becomes visible when the corresnponding player entity is tagged with SEEN_CTHUN, that tag is applied at the same time the C'Thun proxy shows on up the side of the board.
