### ISSUE TITLE
PluginExamlpe error

### ISSUE THREAD

**Issue by HEPEBAP** [HearthSim/Hearthstone-Deck-Tracker#2484]
Hi **@Epix37 **

I tried to run PluginExamlpe, but i got compile error

> The tag 'Card' does not exist in XML namespace 'clr-namespace:Hearthstone_Deck_Tracker.Controls;assembly=HearthstoneDeckTracker'. Line 17 Position 14.

That error for this line `<hdt:Card></hdt:Card>` in **CurvyList.xaml**

**Comment by andburn** [comment]
@HEPEBAP For reasons below I think you must be referencing the regular HDT release. A solution is to the build HDT from source and reference `HearthstoneDeckTracker.exe` and `HearthDB.dll` from the `Hearthstone Deck Tracker\bin\Release` or `Hearthstone Deck Tracker\bin\Debug` directories.

@Epix37 I had a similar query from someone before, with the stats plugin. I thought then it was just something to do with their setup. It turns out there seems to be a problem compiling plugins if you reference the regular HDT release, and attempt to use that reference in xaml.

```
xmlns:hdt="clr-namespace:Hearthstone_Deck_Tracker.Controls;assembly=HearthstoneDeckTracker"
```

Looks like its down to the renaming in the HDT post-build

```
ren "..\Hearthstone Deck Tracker\HearthstoneDeckTracker.exe" "Hearthstone Deck Tracker.exe"
ren "..\Hearthstone Deck Tracker\HearthstoneDeckTracker.exe.config" "Hearthstone Deck Tracker.exe.config"
```

The spaces mess the reference up as far as the xaml is concerned. Compiles fine if you use the `Debug` or `Release` versions directly, or if you just rename the files to remove the spaces again. I'll make a note of it on the plugin readme.

**Comment by HEPEBAP** [comment]
ty, it's work after compile version from source and add reference
