### ISSUE TITLE
Arena Games Sync Problem

### ISSUE THREAD

**Issue by Jouvart** [HearthSim/Hearthstone-Deck-Tracker#2505]
Hello,

Auto update put my 1 complete arena run as 2 arena runs incomplete and 2 arena decks.

So I reset my runs at Hearthstats.

Now when I try to do force sync to get my old arena run stats/decks on site nothing happens.

Isnt there an option to manually update my arena _runs_ to web page so I have my stats updated and sorted.

If that bug didnt happen I wouldnt have reset my stats either.. 

After that I started playing new run and it recorded as normal.

**Comment by Jouvart** [comment]
by the way it works flawlessly at my computer (hence) saved data on ssd.

I wish sync doesnt corrupt our data, at web page.

**Comment by Jouvart** [comment]
I am still trying to understand how I can `export` 1 deck which includes all `arena run` data into hearthstats. 
Sync not doing, if you deleted manually from web page.

**Comment by goldenmane** [comment]
Yes the arena is not syncing at all with the hearthstats, it used to log in completely different things at first (2-2 arena still going) when i was 5-3, now its not syncing at all after reset. Seems pretty useless.

**Comment by goldenmane** [comment]
Alright it seems that it doesn't upload the games that you add by yourself. I downloaded my decks from Heartarena then i wrote in the stats by myself of each game. I wanted to upload that cause those are games I've played before using the tracker only Heartarena. It works and syncs fine with tracker but when adding games by yourself it won't sync don't know why would save me a lot of typing but I already entered all manually to Heartstats too so it doesn't matter anymore. Would be nice if you could fix sync with arena stats imported manually, perhaps the problem here is the lack of turns and play time? It is at 0, so it might not record that as a game or something?

**Comment by judge2020** [comment]
Hearthstats has been discontinued, please see #3235 for the new feature HSReplay is planned to have. @Jouvart

**Comment by judge2020** [comment]
duplicate of #3235
