### ISSUE TITLE
I wonder log.config is too heavy for hearthstone

### ISSUE THREAD

**Issue by jzlhll** [HearthSim/Hearthstone-Deck-Tracker#2660]
Even though without HDT opening, hearthstone will be frozen for a while.  Especially, after my turn started, mouse on a card which have a battlecry point to a minion. Or playing a AOE spell, destory too many minions. I wonder if it maybe too many IO read/write...maybe  log.config is too heavy for hearthstone? It's just some speculation

**Comment by Epix37** [comment]
Well, does deleting it fix your issues?

There are several issues on this topic: #1097, #1274

Generally, the issue was fixed ever since HDT switched `ConsolePrinting` to `FilePrinting`. I haven't heard much of performance complains since.

 If you are still experiencing problems the most likely cause would be your AV. Try adding exemptions for `%LocalAppData/Blizzard` and `[HearthstoneInstallation]/Logs`.

**Comment by jzlhll** [comment]
thinks for response I will check it again.
