### ISSUE TITLE
How do I change the view in the Replayviewer?

### ISSUE THREAD

**Issue by xtreemmasheen3k2** [HearthSim/Hearthstone-Deck-Tracker#2740]
When I started out with Hearthstone, I remember it was my view on the bottom, and my opponent's view on top, But now it's been switched for some reason. Is there any way I can change it back? It's not exactly easy to find.

**Comment by azeier** [comment]
There is no way to change it currently. This is due to the fix to replays after the latest hearthstone update, causing "player 1" to always be the bottom player instead of the "local player". 

*However*, there is something new coming for replays very soon (next few days), making the current replay viewer obsolete! Stay tuned :).

**Comment by jleclanche** [comment]
@xtreemmasheen3k2 Hey, we just announced the HSReplay.net HDT beta! Download the Beta channel here if you want to try it out: https://github.com/HearthSim/HDT-Releases-HSReplay/releases/download/v1.0.5.24/HDT-Installer.exe
