### ISSUE TITLE
double click to edit deck not working

### ISSUE THREAD

**Issue by cachirro** [HearthSim/Hearthstone-Deck-Tracker#2779]
either i'm going crazy here, or i could swear that before when i double clicked on a deck it would open the edit deck mode, now i have to right click and select edit deck.

is it possible to return to old method or put in options a method selection?

thanks

**Comment by azeier** [comment]
Double click was changed in the latest hsreplay beta release to activate the deck instead. Since deck importing from the game works rather well now (last issues with updating changes properly will be fixed with the next release - currently, reselecting the deck fixes it), having double-click to edit seems unnecessary.

**Comment by cachirro** [comment]
you could add in app preferences something like:
double click setting:
- edit deck
- select deck
- archive deck
- etc etc

just my 2 cents

**Comment by azeier** [comment]
I'm trying to get rid of options that are not really necessary at the moment. This is not one I want to add one for. 

Why do you need to edit decks in HDT on a regular basis? Maybe there's a better solution.

**Comment by cachirro** [comment]
i do a lot of edits in my decks, i have some decks with 20+ versions, add a new card, remove another, etc..

think i spend more time testing than actually playing :)

**Comment by azeier** [comment]
I guess my main point is: you can do the same thing directly in hearthstone and HDT will automatically pick up on any changes. Assuming the `options (advanced) > tracker > importing > constructed` settings are enabled.

**Comment by cachirro** [comment]
Hmm, had no idea of that feature, if so, then yes, my suggestion is no
longer needed

Thanks

**Comment by azeier** [comment]
I think it was turned off by default when coming from an old HDT version with a certain setting disabled.

That said, this feature currently has a minor bug where the UI/deck tracker doesn't always pick up on minor changes in decks. Reselecting the deck (in HDT) solves that and the next update will fix it. Just fyi :).

I'm gonna close this then, great!

**Comment by MyopicCat** [comment]
Late to the party, but let me add my two cents anyway. I really miss double-click to edit. I'm a long time user of HDT and all my deck building and editing is done in the tracker. It's just so much faster and easier than doing it in Hearthstone. I don't use hsreplay, so now double-clicking on the deck does absolutely nothing instead of something very useful. Please at least give us an option to enable it!
