### ISSUE TITLE
Metastats plugin not found

### ISSUE THREAD

**Issue by ScottAllen11** [HearthSim/Hearthstone-Deck-Tracker#2889]
Problem: No plugins are listed.

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/527451/hdt_log.txt)

I have extracted the Metastats folder with its dll to AppData > Roaming > HearthstoneDeckTracker > Logs. This is the same folder that HDT opened when I hit the plugins buttons. Structure looks correct.

I have right-clicked the dll to unblock it and verified the option is now gone.

I have restarted HDT several times, and have even restarted my Windows 10 PC.

Would like to contribute to Metastats. Any ideas for making it appear so I can enable it will be appreciated.

Scott

**Comment by andburn** [comment]
The plugins should go in `AppData\Roaming\HearthstoneDeckTracker\Plugins`, it looks like that is where you put the files according to the log.

The problem is you have installed HDT in `C:\Program Files`, this is causing a problem.
It is recommend to use the new installer version of HDT at https://hsdecktracker.net/download/.
But, if you must use the *zip* file version, extracting it somewhere else like `C:\HDT` will work.
