### ISSUE TITLE
Bug: Tracking opponents Stats instead of own

### ISSUE THREAD

**Issue by shamanix7** [HearthSim/Hearthstone-Deck-Tracker#2950]
I won a game after my opponent left just before lethal. In HDT, my opponents stats are tracked (loss, PlayerName him, OpponentName me).
Attachments: Screenshot, DeckStats, Log
[opponentTracked.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/598549/opponentTracked.zip)

**Comment by azeier** [comment]
Interesting issue.

Hard to tell what caused this or how it could even happen. Might not be worth worrying over.

Please let me know if you notice this again.

For future reference: most likely fix (actual issue is likely .IsPlayer not working correctly - tag not set?) should be something along these lines 
```diff
HandleGameEnd()
{
    ...
-    var player = _game.Entities.FirstOrDefault(e => e.Value?.IsPlayer ?? false).Value;
-    if (player != null)
-        _game.CurrentGameStats.PlayerName = player.Name;
+    _game.CurrentGameStats.PlayerName = _game.Player
    ...
````

**Comment by judge2020** [comment]
Is this still an issue @shamanix7?

**Comment by shamanix7** [comment]
It hasn't occured on my HDT

2017-05-15 16:32 GMT+02:00 Hunter <notifications@github.com>:
