### ISSUE TITLE
Different Players - One Computer

### ISSUE THREAD

**Issue by notNDAface** [HearthSim/Hearthstone-Deck-Tracker#2971]
So my wife likes to play hearthstone on the same computer. I'd like to set up a seperate instance of the deck tracker to keep track of her decks and stats seperate from mine, but I can't figure out how to do it. I've tried installing two copies of the tracker in different directories, but it seems to be pulling from the same data folders. I tried turning off saving config and data to the app directory in one instance, but that seemed to erase the decks in both of them.

I'm stumped. Any idea?

**Comment by azeier** [comment]
This is not entirely supported right now, but it's something I plan on adding - hopefully somewhat soon.

Turning off "save config/data in appdata" should be the correct approach: Try doing that for one of the instances, then copying that installation. Make sure not to run one of the existing installations after installing a fresh one until you turned off those options as well (which is only possible in the portable (zip) download), otherwise that state will be used.

**Comment by judge2020** [comment]
A feature to sync HDT between computers is in the works with hsreplay. A good issue to combine these requests in is #3235.

**Comment by judge2020** [comment]
duplicate of #3235
