### ISSUE TITLE
Not tracking after reconnecting

### ISSUE THREAD

**Issue by JulioCL** [HearthSim/Hearthstone-Deck-Tracker#299]
The game result is not tracked after reconnecting mid-game and finishing it.
Here is the last part of the log from that game

http://pastebin.com/GuccFQDc

**Comment by culinko** [comment]
There should be a way for the tracker to record the matches after reconnect/restart of the game. Yeah, maybe you miss a turn or two, but it should know when the match started (and all the other info like opponent class, coin and such) and then just wait for the result. It's still better than a missing match. I was able to scramble something from the incomplete replay file, the only "mystery" for me was the number of turns. Does the log store the turn number related to start of the match or does it count over again from the moment you reconnected into the game?

Also on unrelated note, when I tried to link the incomplete replays to the games and running them by the tracker, it threw like 100 exceptions, so maybe you might want to display a warning if the replay file is damaged. Maybe that's unnecessary, because who would ever try to do that, but I was still surprised that so many error messages popped up. I can upload those replays if you want them.
