### ISSUE TITLE
Deck Tracker dropping Jade Cards

### ISSUE THREAD

**Issue by Almagnus1** [HearthSim/Hearthstone-Deck-Tracker#2992]
I'm trying to experiment with the Jade Lotus cards on druid, and the deck tracker keeps dropping all the MSoG cards from my deck partway through a match, so either I have to add in the missing cards mid match, or start mentally tracking stuff to figure out what's missing.

**Comment by HoopyHobo** [comment]
Yeah, in the middle of a game usually when a draw happens all of the MSG cards in all of my decks get removed.

**Comment by azeier** [comment]
Could you guys upload logs for games where that happens?
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by HoopyHobo** [comment]
The problem is with HearthStats. They haven't updated for MSG, so syncing to a decklist saved there wrecks your local copy. HDT works fine when not signed into HearthStats. Not sure how useful this log is, but I'll share it anyway:

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/629127/hdt_log.txt)

**Comment by azeier** [comment]
Oh! That is good to know. Thank you for the info.

**Comment by azeier** [comment]
"Fixed" with v1.1.3
