### ISSUE TITLE
Broke in 8.0.0.18336

### ISSUE THREAD

**Issue by chWolfgang** [HearthSim/Hearthstone-Deck-Tracker#3150]
## Before we start
- Please doublecheck there is no existing issue for your problem/feature request.  
- Please delete any obsolete sections (including this one) from this template before submitting your issue.

## Bug report
As of patch 8, the HDT is not updating during games. No decks, no card turn info in appointments deck, etc.
### Expected Behavior
To be able to read current game status/information

### Actual Behavior
Appears to not be able to gather information on current game.

### Steps to reproduce behavior
- Step 1 closed HDT and HS
- Step 2 Opened HDT then HS

### Log/Screenshots
If applicable, provide a log of the session where the problem occoured.  
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by djdookie** [comment]
I got the same problem.

**Comment by azeier** [comment]
Working on it :).

**Comment by CobbHS** [comment]
My deck tracker is showing on my screen, but it's only showing my deck. It won't highlight any of the cards I draw or do any of the other things it did yesterday. I'm assuming it has something to do with the update that came out this morning, (April 4th, 2017). It is a bit frustrating because I am so used to being able to know what I'm drawing, etc. I've already re-installed a couple times. Somebody please help. Thank you. :)

**Comment by azeier** [comment]
> Working on it :).

**Comment by Drui7** [comment]
Please update the translation along with the program fixes
https://github.com/HearthSim/HDT-Localization/pulls

**Comment by Poetro** [comment]
Thanks!

**Comment by djdookie** [comment]
Thanks for the fixed new release. Works fine again now!

**Comment by azeier** [comment]
Everything should be (mostly) good now with 1.2.1 :).
