### ISSUE TITLE
upload the game record failed

### ISSUE THREAD

**Issue by chucklu** [HearthSim/Hearthstone-Deck-Tracker#3186]
### Expected Behavior
upload the record successfully

### Actual Behavior
can not upload the record most time,need to try lots of times
more information can be found in https://github.com/HearthSim/HSReplay.net/issues/263
![default](https://cloud.githubusercontent.com/assets/3004057/24652015/9c43f282-1962-11e7-81be-938ada5da29d.PNG)

### Steps to reproduce behavior
- Step 1  upload the record in China

### Log/Screenshots
[log3.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/908433/log3.txt)

1:15:07|Error|LogUploader.TryUpload >> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 54.231.73.75:443
   在 System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
unable connect to remote server

**Comment by chucklu** [comment]
After lots of times uploading ,I can upload the record finally.
Is it possible to config the reupload times in setting?

**Comment by beheh** [comment]
This does appear to be connection issues, so a reupload/retry setting would help alleviate this problem.

**Comment by jleclanche** [comment]
I don't really know what we can do there. There's already a retry with backoffs in HDT which should be good enough for most cases, but the API server being in the USA means it won't necessarily be reachable from China.

We're getting a fair amount of uploads from China though so this is maybe something you can fix with your provider, I dunno :/ Closing because there's nothing more we can really do I think.
