### ISSUE TITLE
Unclickable buttons in HS client

### ISSUE THREAD

**Issue by NightOnEarth** [HearthSim/Hearthstone-Deck-Tracker#3287]
Hey folks,

when i export a deck to Hearthstone it seems to choose golden cards by default now. If i remove the golden cards and add the non golden ones (BEFORE i click done after the export) i cannot click any button in the HS client anymore , nor add or remove any cards. Only button still working is the game menu button in the lower right. 

If i export the deck, then hit done after the export without switching any cards everything is fine. 

(On a sidenote:  is the option to prioritize non golden card gone now? I could not find it in the options, please bring it back :) )

**Comment by judge2020** [comment]
HDT (the deck tracker) no longer controls exporting to hearthstone with the addition of deck strings. The Hearthstone client is the one that controls adding golden/regular cards.

The button messing up isn't HDT either, possibly post in [hs-bugs](https://github.com/HearthSim/hs-bugs/issues).

**Comment by judge2020** [comment]
A solution to the export golden/non-golden selection option would be to have an option in settings to use the old exporting mechanism.

**Comment by NightOnEarth** [comment]
Good idea judge2020, i would definetely prefer the old exporting mechanism over the new one, an option for using it would be very nice indeed. 

Otherwise managing / exporting multiple decks will get a nightmare. I would have to export, then click done, then click the deck again, then remove all the golden cards, then navigate to the non golden ones and put them into the deck. 

Doing the whole deck manually in the first place seems almost faster.

**Comment by azeier** [comment]
We don't be adding back the old exporting system, sorry. It's something I really don't want to maintain when there's an official system in place that does the job (with this exception) better than ours in the first place.

You'll have to ask Blizzard for it. They have a way in arena now to remove golden cards, adding the same thing for constructed is not unreasonable.

Closing this since the original issue is a problem with Hearthstone, not HDT.
