### ISSUE TITLE
skulking geist+quest

### ISSUE THREAD

**Issue by freakaz0id1** [HearthSim/Hearthstone-Deck-Tracker#3373]
### Expected Behavior
upon playing skulking geist and having quest in my deck deck tracker should delete the quest from the list

### Actual Behavior
the quest still shows up as if it is still in my deck

### Steps to reproduce behavior
mulligan away the quest, play skulking geist

**Comment by azeier** [comment]
Is the quest somehow not revealed on discard? Not sure why this would happen.

Please reproduce it and post the HDT log here - https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by djdookie** [comment]
The quest ist not revealed or discarded, it is destroyed in your deck by skulking geist (like all other 1-mana spells).
If I understand @freakaz0id1 correctly, HDT doesn't recognize when spells get destroyed in your deck?

**Comment by azeier** [comment]
Destroyed cards are still discarded for all intents and purposes. They get moved from HAND/DECK to REMOVED (or maybe SETASIDE). And they are revealed,   that's why you see them in the history in game and that's the entire reason HDT is able to remove them from the deck/show them on the opponent side.

The only exception for that seems to be quests.
