### ISSUE TITLE
Installer Needs to ask for a location

### ISSUE THREAD

**Issue by Almagnus1** [HearthSim/Hearthstone-Deck-Tracker#3600]
### Expected Behavior
On install, I expect the installer to ask for a location, and not automatically assume that it's to be installed in the profile directory.

### Actual Behavior
Installer automatically sticks files wherever it pleases without telling you what is going where.

This means that if you are running the deck tracker from a location (like D:\ that's on a second hard disk), the installer will assume you are running it out of the profile directory, and completely fail to update the tracker as expected.

### Steps to reproduce behavior
Run the installer, and note that it doesn't generate logging saying what it's doing - which is VERY reminiscent of the adware from the 90's.

**Comment by azeier** [comment]
you can download a portable build here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/latest

**Comment by Almagnus1** [comment]
The install process you're using is fitting of a store app... NOT a desktop application.

The issue is your installer is not properly configured - not using a portable version.

**Comment by judge2020** [comment]
The installer's main purpose is to seamlessly install the application in order to simplify the process, and make it *feel* like a modern app store-type app where installations and updates just work.

The installation and AppData directories only take up ~150 MB, which isn't much as SSD and hard drive storage prices keep getting cheaper.

For those that do want to control where installer files end up, the portable version is still maintained and likely won't be going anywhere for a while.

**Comment by Almagnus1** [comment]
Point I'm making is the behavior that you're describing only makes sense when the app is coming from a store.

Hearthstone Deck Tracker should work like every single other application and ask for an install location, or (at minimum) state where the install is going.  This silent install behavior is bad practice - and makes the app feel like malware.

**Comment by azeier** [comment]
Thanks for your opinion.
