### ISSUE TITLE
Tried everything on fixing my decktracker to show my cards being used on the overlay

### ISSUE THREAD

**Issue by Xlantis** [HearthSim/Hearthstone-Deck-Tracker#3921]
### Expected Behavior

the tracker to grey out the cards I have used in a match and drawn. And to show the cards my opponent is using
### Actual Behavior

just shows my full deck but doesnt count down the cards or show opponent cards
### Steps to reproduce behavior

Not sure 
### Log/Screenshots

[hearthstone_2019_06_03_14_16_58.log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/3249151/hearthstone_2019_06_03_14_16_58.log)

**Comment by Xlantis** [comment]
Also I tried to leave a screenshot but it doesnt show my deck tracker in the screenshot IDK why

**Comment by Zesaric** [comment]
Same here, I believe it's a result of the latest HS patch (v14.4 from 3 June 2019) because I played today with HDT working fine before the patch and now got the same behaviour as Xlantis after the patch.
Re-installing Battle.net, Hearthstone and HDT did not fix the issue so I am quite sure there is an incompatibility between the latest HS and HDT releases.

**Comment by azeier** [comment]
v1.8.11 is now out and should fix any issues caused by the Hearthstone patch
