### ISSUE TITLE
HSReplay.net global statistics not available for often-played decks known to HSReplay.net

### ISSUE THREAD

**Issue by Gorilla801** [HearthSim/Hearthstone-Deck-Tracker#4031]
## Bug report
After using HSReplay to netdeck and import using Deck Code to HDT, Global statistics not available for that deck, ver. 1.10.6

### Steps to reproduce behavior

 Go to https://hsreplay.net/decks/GKsZDZ6Iipu07shufa5mBg/
 Import to HDT using deck code.
"We don't have enough data for the selected deck." shows in Global Statistics
(This URL not cherrypicked, happens every time now)

**Comment by azeier** [comment]
Thanks for the reminder. We had to update lots of APIs and I forgot the ones HDT uses.

This will be fixed with v1.10.7, which should get released later today, whenever the Hearthstone client update goes live which it did right now, while writing this. -- Which it did right now while writing this. The new version should get released in the next two hours or so.

Once v1.10.7 is released it may take up to 24 hours for HDT to evict the old deck data from cache, depending on when it was last updated. To speed this up, the `%AppData%/HearthstoneDeckTracker/hsreplay_decks.cache` file can be deleted while HDT is not running.
