### ISSUE TITLE
*potential GitHub candidate* HELP? (looking for answers to simple brief questions about github and its applications!)

### ISSUE THREAD

**Issue by erictheeawful** [HearthSim/Hearthstone-Deck-Tracker#4059]
GREETINGS, I'm a frequent hearthstone player, user of HDT, and how HearthSIM is something like a browser-friendly tracking database that is written in java or an html-like code exported from HDT in someway i'm not so sure, but i'd like to know more.

I have some solid Python-coding background during my undergrad & some (likely outdated) intermediate level html code-writing from 15 years ago (back in the day when it was more time-consuming and more underdeveloped.) I also worked much with Rstudio during my undergrad. I'm not exact on the correct term in which to classify that software but somehow i feel like it may apply in some way perhaps or may serve useful for my own personal means of data-analysis?!

I think from what i've explored so far about github, it is something I may contribute to! I just have a few straight-forward questions:

 - _where should have I properly posted this inquiry?_
 - **HDT is a great utility that I am glad to have access to. but there are additional functions I'd like to see HDT track. I'm willing to write and work them myself if I was better informed or pushed in the right path.** is HDT freeware?, for e.i. - is it possible for me to have my own 'experimental' functions and stats displayed in HDT? or is this what github is? a place for people like me tinkering with a browser-version?
 - is hearthsim affiliated with HDT? is HDT coding/addon construction the same thing? (am I in the right place talking to the right people? I guess my question is) 
 - I briefly explored the guide? it repetitively proposes "no coding exp. needed". I'd like to skip the tutorial sort to speak and jump right in? what kind of coding would I be looking at?
- could my own python build aid me in anyway if I got into this github team? cause I really enjoy python!
- also is there anyway Github could lead me to employment opportunities?

**Comment by DayKev** [comment]
> where should have I properly posted this inquiry?

A good place to start is the [developer Discord](https://discord.gg/hearthsim-devs) server.

> is HDT freeware?, for e.i. - is it possible for me to have my own 'experimental' functions and stats displayed in HDT? or is this what github is? a place for people like me tinkering with a browser-version?

HDT is free & open source; you can contribute to it directly or make plugins that hook into it.

> is hearthsim affiliated with HDT?

Yes, HDT is a HearthSim product (along with [HSReplay.net](https://hsreplay.net) and a few other things).

>could my own python build aid me in anyway if I got into this github team? cause I really enjoy python!

Unfortunately HDT is made in [C#](https://en.wikipedia.org/wiki/C_Sharp_\(programming_language\)), though you might be able to use [IronPython](https://ironpython.net/) which is "an open-source implementation of the Python programming language which is tightly integrated with the .NET Framework. IronPython can use the .NET Framework and Python libraries, and other .NET languages can use Python code just as easily."
(C# being a ".NET" language)

You probably couldn't contribute to HDT itself with that (unless you don't mind just having your own personal build that you need to keep up-to-date manually), but using it to make plugins shouldn't be a problem. Also note that IronPython is based on the 2.x version of Python, so you won't have access to any of the new features of Python 3.x (though since you have access to C# you can use its features in their place).

> also is there anyway Github could lead me to employment opportunities?

Probably. I could have sworn Github had some sort of "careers program" to aid in this, but I might be confusing them with another org. 🤷‍♀️ If nothing else, it would probably help with getting a job [at Github itself](https://github.com/about/careers). 😉
