### ISSUE TITLE
HDT on wine re-run as a normal user

### ISSUE THREAD

**Issue by stanig2106** [HearthSim/Hearthstone-Deck-Tracker#4106]
## Bug report
Can't install HDT on wine because wine only start app with administrator right

### Steps to reproduce behavior
Try to install HDT-Installer.exe on wine

### Log/Screenshots
![Sans titre](https://user-images.githubusercontent.com/65514998/85206554-4e78fa80-b323-11ea-8c2d-ef0918b71d8c.png)

**Comment by Alaharon123** [comment]
I believe the command to run not as administrator is `wine runas /trustlevel:0x20000`

Also be sure to install dotnet with winetricks.

That being said, this program does not work well on WINE at all. Unusable. Arena Tracker is the only working Linux overlay I know of. If you search issues here, you'll find multiple threads about using this on WINE and they're all disappointing

**Comment by Alaharon123** [comment]
Edit: runs with instructions at https://github.com/borisbabic/hearthstone_hdt_linux

**Comment by stanig2106** [comment]
Thanks for the reply, for now I am using wsl so I no longer need wine
Hope it helps someone else

**Comment by Snahier** [comment]
Regarding the **runas** command.
It seems that newer versions of wine have removed the dll/exe for **runas** due to a bug that hasn't been fixed yet.

So once I try to run that command I get the following error:
`0024:err:module:process_init L"C:\\windows\\system32\\runas.exe" not found`

Is there any way to install stuff without having to rollback to older versions?
