### ISSUE TITLE
Agamaggan, the Great Boar is incorrectly related to battlegrounds beast pool

### ISSUE THREAD

**Issue by gorttar** [HearthSim/Hearthstone-Deck-Tracker#4302]
### Expected Behavior
Agamaggan, the Great Boar should be in the Quilboar Pool despite he is a beast similar to Nadina the Red is in the Dragon Pool despite she is not a dragon
### Actual Behavior
Agamaggan, the Great Boar is currently in the Beast Pool

**Comment by gcaliber** [comment]
I believe it fails because this is the first and only minion that doesn't mention the battlegrounds race it belongs to in the card text, it only mentions the race's mechanic of blood gems. The fix would probably be to look for both a race itself and the race's mechanic in the card text in order to classify it properly.

**Comment by Jonysegal** [comment]
Fix in progress, thanks for the alert!

**Comment by Jonysegal** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/pull/4303 if you're curious
