### ISSUE TITLE
[Feature request] Prevent automatically disabling plugins

### ISSUE THREAD

**Issue by Kryptortio** [HearthSim/Hearthstone-Deck-Tracker#4365]
The plugin I use keeps getting disabled, presumably this is because it is out of date. I keep enabling it and it works fine anyhow. So please let me prevent it from getting disabled somehow.

- Add option to not check version for plugins?
- Add option to not check version for specific plugins?
- Disable version check and only disable plugins if they crash?
- Only disable plugins is the application crashed last time?
- Ask before disabling a plugin?

Please consider one of the options above or similar, it wastes a lot of time having to manually re-enable plugins all the time.

**Comment by alexbereznikov** [comment]
Please correct me if I'm wrong, but in my experience plugins are disabled when they're crashed. Would you mind attaching the latest HDT log file having the issue with disabled plugin reproduced?

**Comment by Kryptortio** [comment]
I found the logfile but no issues with the plugin I was using (PackTracker.dll), however I did find that I had an old dll of a different plugin that did have an issue and wasn't getting loaded at all. After deleting that one (HearthstoneCollectionTracker.dll from 2016-04-27) it seems to work better (several restarts without packtracker getting disabled). Can this be what was causing the issue? Will all plugins be disabled if one is having a problem?

**Comment by alexbereznikov** [comment]
I'm not a HDT developer, so can't tell for sure. In my opinion (especially given that it fixed the issue) yes, likely that was the issue. Maybe loading of this dll might affect other plugins, but in general I think only crashed plugin should be disabled. I'm trying to create something like ArenaHelper replacement in my spare time (since it is abandoned for a while) and each time my plugin crashes it gets disabled, that's all I know.

**Comment by Kryptortio** [comment]
Still hasn't been disabled so I guess I'll close this for now although I guess add-ons interfering with each other might be a separate issue.
