### ISSUE TITLE
Spell schools not attached to Card object

### ISSUE THREAD

**Issue by slicedbread** [HearthSim/Hearthstone-Deck-Tracker#4421]
### Expected Behavior
I'm trying to write a plugin for multicaster and I need access to played cards' spell schools

### Actual Behavior
The data isnt mapped from hearthdb

I've actually made a branch locally to rectify this but I can't find how to contact the team for this repo to request the ability to make a branch on remote. I reached out on discord and haven't had any luck. I recognize this is probably not the best place to make this request but if I could be given permission to make a PR I'd appreciate it.

**Comment by beheh** [comment]
Hello, thanks for wanting to contribute! The standard way to do this on GitHub is for you to create a fork of this repository, push your branch there, and then open a PR here. [Here's a help article from GitHub with all the steps](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request). Let me know here if you have any more questions, otherwise I'll see you over in your PR!

**Comment by slicedbread** [comment]
Awesome, I didnt realize I was supposed to fork, but that makes sense thanks.

The link to that agreement doesnt seem to work, can you provide me the agreement to sign?

**Comment by beheh** [comment]
I've sent you [an invite](https://github.com/HearthSim/cla/invitations)!

**Comment by slicedbread** [comment]
signature PR'd!

**Comment by slicedbread** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/pull/4423
