### ISSUE TITLE
A better way to track stuff in mercenaries

### ISSUE THREAD

**Issue by pep0w** [HearthSim/Hearthstone-Deck-Tracker#4431]
1. I'd like to have a way to collapse the secrets list with a button above the list. It gets in the way, especially in wild where there are like 100 secrets that the enemy can play.

2. I often play mercenaries, and when trying to quickly complete tasks there is no way to track how much damage i've done, how many enemies i've killed, how many turns i've used (what is the turn limit there?).
If damage, kills, and other stuff is just not possible to be added, then can we at least have a turns counter..? So we know when the game will end in a draw/defeat...

Thank you.

**Comment by q1k** [comment]
I'd like to add that now with the latest update all tasks from all mercenaries can be completed at any time. This makes the tasks panel huge and unreadable.
The panel will need to be reorganized to show only active mercenaries tasks. As well as the other daily tasks. A two column layout would be good here. Or a pagination system could also solve this I guess.

**Comment by gribos** [comment]
complett

> I'd like to add that now with the latest update all tasks from all mercenaries can be completed at any time. This makes the tasks panel huge and unreadable. The panel will need to be reorganized to show only active mercenaries tasks. As well as the other daily tasks. A two column layout would be good here. Or a pagination system could also solve this I guess.

completely agree tasks after last HS update are unreadable,  panel should have some scroll or filter to find only Mercs which i use in me team

**Comment by VeXHarbinger** [comment]
I understand what you'd suggest collapsable, but I'd like to offer the suggestion of scoping the Tasks query to just the Mercs in the party on the run.  I'd hazard a guess that most folks look at the campfire when looking to see what tasks can be resolved, then they build the party.  So a scoped task list would at least remind the player who needs a Dmg tatal vs what skills they are supposed to be using, or if you added them just because it was a party req.  I just don't see a point is seeing tasks for mercs not in the party or run

**Comment by beheh** [comment]
I've moved the secrets list request to #4561. I'm closing this as we're not currently planning on making further changes for Mercenaries.
