### ISSUE TITLE
Banana Slamma odds potentially incorrect?

### ISSUE THREAD

**Issue by RampageGames** [HearthSim/Hearthstone-Deck-Tracker#4467]
I don't have much hard evidence to submit to prove its incorrect, but I feel like it might be worth looking into to see if its calculating it correctly.

The odds vs a guy with a golden Banana Slamma, two mama bears and 4 beast deathrattles summoning more beasts said extremely high odds (96.7% chance of winning and 95.3% chance of winning on two back-to-back turns), yet the turns looked to be decent trades and it was still a loss and a tie... (such as sniping his reborn-buffed ghastcoiler when he had 7 minions on the board, thus blocking 1 of the summons and also blocking the reborn completely).

My inkling is that the Banana Slamma tripling the summoned stats including mama bear buffs isn't taken into account, making it look like the guy was unlikely to win, when in reality it seems more like a 50/50 chance of winning that round.

**Comment by Stoutt** [comment]
It's more than just banana slamma, I've noticed that a lot of teams aren't accurately being calculated. I just lost a 99.7% chance to win and took 23 damage and it wasn't even close and I had a 0.1% chance to die which I did. There was another turn that didn't calculate correctly too but I can't remember when it was in the game. Here's the log so you can see for yourself:
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/11713934/hdt_log.txt)

**Comment by Jarelk** [comment]
Can just confirm I lost three 99.9% wins in a row, using a bassgill team.

**Comment by RampageGames** [comment]
> Can just confirm I lost three 99.9% wins in a row, using a bassgill team. Considering those astronomical odds, I assume the tracker was just wrong.

It definitely is, my friend lost a 100% win 100% lethal while he had bassgills.

**Comment by beheh** [comment]
Thanks for the report!

There's a few factors here:
- Overall we're aware of the types of cards that are problematic because we have fairly sophisticated monitoring in place for issues like this.
- Keeping the odds working is a moving target, and we're constantly making changes to improve the accuracy if we deem it too bad. In this case I'm fairly sure we've fixed the specific bug for this card at this time.
- Banana Slamma specifically is not in the game right now

I think we can safely close this specific issue for now.
