### ISSUE TITLE
Database - Buddies cards not updated

### ISSUE THREAD

**Issue by WittR** [HearthSim/Hearthstone-Deck-Tracker#4558]
### Expected Behavior

Get the updated cards of the buddies in the Database

### Actual Behavior

New buddies and reworked buddies are not updated in the Database (for example Yogg Saron' buddy (TB_BaconShop_HERO_35_Buddy) :
Former version : https://hearthstone.fandom.com/wiki/Battlegrounds/Acolyte_of_Yogg-Saron
Updated version : https://hearthstone.wiki.gg/wiki/Battlegrounds/Acolyte_of_Yogg-Saron 

Thanks a lot !

**Comment by beheh** [comment]
Hey there! Can you clarify *where* they're not updated? Is this about card images or HearthstoneJSON or something? To my knowledge they wouldn't be shown anywhere in HDT.

**Comment by WittR** [comment]
Thanks for answering!

These cards (images) are actually not used by HDT, but I use them in a plugin (displaying buddies during streams). I thought all the cards in the HDT Database API would have been updated eventually. Do you think this database can be updated, or will it remain an unused legacy?

Thanks for your time.

**Comment by beheh** [comment]
I'm still a little confused. The image is updated in HearthstoneJSON (<https://art.hearthstonejson.com/v1/bgs/latest/enUS/256x/TB_BaconShop_HERO_35_Buddy.png>) and the card should be up-to-date in HearthDB as well. Can you show an example of the code where you're retrieving something about this Buddy and are seeing outdated data?

**Comment by WittR** [comment]
Hello! Thanks again for taking the time to help with my issue.

Here's the code I'm using:
`CardImage.SetCardIdFromCard(Database.GetCardFromId("TB_BaconShop_HERO_35_Buddy"));`

I'm new to HDT plugins, so I appreciate your patience !

**Comment by beheh** [comment]
Are your cards showing mana crystals in the top left corner by any chance? In that case you might be accessing the normal renders ([https://art.hearthstonejson.com/v1/render/**latest**/enUS/256x/TB_BaconShop_HERO_35_Buddy.png](https://art.hearthstonejson.com/v1/render/latest/enUS/256x/TB_BaconShop_HERO_35_Buddy.png)) instead of the Battlegrounds render ([https://art.hearthstonejson.com/v1/**bgs**/latest/enUS/256x/TB_BaconShop_HERO_35_Buddy.png](https://art.hearthstonejson.com/v1/bgs/latest/enUS/256x/TB_BaconShop_HERO_35_Buddy.png)).
We no longer update the mana crystal versions, to sped up our rendering pipeline after a new patch and because they're not used anywhere.

From your code it seems you're probably using the CardImage class, which [downloads the image](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/48eb93381ab2927a044ea9a789c00f6cb8932939/Hearthstone%20Deck%20Tracker/Controls/CardImage.xaml.cs#L128C21-L128C57) via the [`cardImageDownloader`](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/48eb93381ab2927a044ea9a789c00f6cb8932939/Hearthstone%20Deck%20Tracker/Utility/Assets/AssetDownloaders.cs#L58-L66). That class [loads the Battlegrounds version](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/48eb93381ab2927a044ea9a789c00f6cb8932939/Hearthstone%20Deck%20Tracker/Utility/Assets/AssetDownloaders.cs#L60C77-L60C86) if you set [BaconCard](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/48eb93381ab2927a044ea9a789c00f6cb8932939/Hearthstone%20Deck%20Tracker/Hearthstone/Card.cs#L610) to true on the card.

Try updating your code like this:
```cs
var card = Database.GetCardFromId("TB_BaconShop_HERO_35_Buddy");
card.BaconCard = true;
CardImage.SetCardIdFromCard(card);
```

**Comment by WittR** [comment]
Thank you very much, it works !
