### ISSUE TITLE
Sometimes automatic updates don’t work

### ISSUE THREAD

**Issue by obsidiandog** [HearthSim/Hearthstone-Deck-Tracker#4569]
### Expected Behavior

I want to automatically update every time I open or restart the software.

### Actual Behavior

Sometimes it updates automatically when I open the software, but sometimes it doesn't, and nothing happens even if I restart the software. I don't know if it's because the Hearthstone update is too new.

### Steps to reproduce behavior

This problem is not frequent, but it often occurs shortly after Hearthstone is updated.

**Comment by beheh** [comment]
Hey! We usually only release the Hearthstone Deck Tracker update ~1h after the Hearthstone update releases. If you restart and nothing happens, it's likely because we haven't released an update yet.

What you could try next time is to watch this page: https://github.com/HearthSim/HDT-Releases/releases - you'll see there once we release a new update.

**Comment by obsidiandog** [comment]
Got it, thank you my friend!
