### ISSUE TITLE
Replay: Fatigue is not registered

### ISSUE THREAD

**Issue by mvy** [HearthSim/Hearthstone-Deck-Tracker#582]
Same as previous entry : 

http://pastebin.com/e1ZeKZ7d

There is no record of the fatigue taken by the opponent in the replay viewer.

Turn 34: Opponent takes 1 fatigue from draw at his turn

Turn 35: Fireblasted acolyte of pain, opponent takes 2 fatigue from overdraw
Blizzard on acolyte of pain, opponent takes 3 fatigue from overdraw

Turn 36: Opponent takes 4 fatigue from draw

Turn 38: Opponent takes 5 fatigue from draw and dies.

**Comment by mikler** [comment]
I can confirm that this is still the issue on hsreplay.net ([sample replay](https://hsreplay.net/replay/DXqbgmSqZqCP7MAahzeVhH)). But this issue is incorrectly filed to Hearthstone-Deck-Tracker project. @azeier, @andburn, @dvide or anybody else, is it possible to move it to the hsreplay.net project.

**Comment by jleclanche** [comment]
Let's move this to HearthSim/Joust#127 then.
