### ISSUE TITLE
Suggestion: Stats category slight reorganisation

### ISSUE THREAD

**Issue by GiggliG** [HearthSim/Hearthstone-Deck-Tracker#799]
At the moment, when you look at the stats page you have:

Deck Overall
Stats Games

Sometimes clicking through those to get the one you want is more laborious than it needs to be. I suggest changing it to:

   ==Deck==       === Overall ==
Stats Games  Stats Games

Or
== STATS ==    == GAMES ==
Deck Overall Deck Overall

So that all 4 options are visible at all times. Maybe switch the order so Overall is first, and if you dont have a deck selected, either hide them or grey out those options.

What do you think?

**Comment by Epix37** [comment]
There's probably a better way than having the tabs. Redoing the stats screen is on my list for the near future. I'll have to play around with it a bit to see what works.

**Comment by Epix37** [comment]
The tabs behave a bit more logical now. 

Selecting stats or games will select it for both deck and overall.

Meaning:

| action | selected tabs |
| --- | --- |
| starting | Deck : Stats |
| click Overall | Overall : Stats |
| click Games | Overall : Games |
| click Deck | Deck : Games |

**Comment by GiggliG** [comment]
That sounds good, but I'd still like something like the suggestion above, so that all 4 tabs are available from a single click.

**Comment by Epix37** [comment]
Yes, I will still redo it in some other way in the future. But this was quick to do and feels a lot better.

**Comment by culinko** [comment]
I was thinking about how we can get rid of the tabs and maybe found out a solution (it's a raw idea, I just moved checkboxes and buttons around the place). I was always surprised that you can see different stats depending on if you have deck selected or not when clicking on "Stats" button on the top.

Few observations (inconsistencies) about the current behavior:

Games tab: 
- "Games" selection is present only in overall tab
- "Apply tag filters" and "Player" selection is present only in overall tab
- "Add new game" button is present only in deck tab (so if the proposed behavior is accepted you need to add "deck name" and "version" as new fields into the game creation popup)

Stats tab:
- "Games" selection is present only in overall tab
- "Apply tag filters" and "Show as percent" is present only in overall tab (in the table itself)
- tables in "Deck" display both % and numbers, table in overall only displays numbers (that's why there is filter) - this is kinda inconsistent, maybe you should be able to choose between "percent" and "both" (default display being the numbers only)

One other observation to note: The "filtering" layout is kinda inconsistent, because the checkmarks and selection buttons are in multiple places (perhaps all the buttons could be added into the filter area instead of being just above the games/stats itself? Those are filters too, you know.

I also injected subtle request that I already asked for in one of the other tickets (sorry, couldn't help myself, i love arenas :P). Finally, here are the two sketches:

![games](https://cloud.githubusercontent.com/assets/11700272/7066734/d7d52afc-dec5-11e4-8d4b-a6b0916f9b17.png)
![stats](https://cloud.githubusercontent.com/assets/11700272/7066737/dc1a1aa0-dec5-11e4-8b73-af3580f2c487.png)

**Comment by GiggliG** [comment]
Personally I like the fact you have Deck - Games and Overall- Games, plus Deck - Stats, and Overall - Stats as separate tabs. I dont see why you couldn't have 4 tabs (5 if you include Arena runs, which is a sensible addition).

Regarding your idea of adding Deck as a Filter: it seems like a good compromise, except it doesn't take into account how many decks some people might have. Switching between Overall and Deck is somethign I do a lot, and being able to do it the current way (two clicks) is much better than having to use a drop down and scroll down a loooong list (I have over a 100 decks in my HDT) to find the one I want to look at. That will tiresome old very fast.

I hadn't noticed all the inconsistencies you point out between the tabs, but those are good observations.

**Comment by Epix37** [comment]
How about this actually: 
![screenshot 2015-04-10 12 06 19](https://cloud.githubusercontent.com/assets/7737910/7085747/2048e9f4-df7a-11e4-960e-5901a61290b3.png)
(the opponents "breakdown" is still a bit WIP)

With this stats would be displayed in a separate window by default. Not sure what to do yet with the space on the left. Probably some more graphs? Card mechanics breakdown, something like that?

**Comment by culinko** [comment]
I don't know, this change would make the window much bigger. Sometimes I just want to look only at my games. But I'm not a UI designer, so :)
